# Generated by Django 4.2.3 on 2023-07-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The catagory of the job.', max_length=200, verbose_name='Job catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the company.', max_length=200, verbose_name='Company Name')),
                ('company_logo', models.ImageField(help_text="The company's logo.", upload_to='static/company_logos/')),
                ('description', models.TextField(help_text='A brief description of the company.')),
                ('website', models.URLField(help_text="The company's website.")),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='The title of the job.', max_length=200, verbose_name='Job Title')),
                ('location', models.CharField(help_text='The location of the job.', max_length=200)),
                ('salary', models.CharField(help_text='The salary for the job.', max_length=200)),
                ('tag', models.CharField(help_text='A tag for the job.', max_length=200)),
                ('catagory', models.CharField(default='', help_text='The experience required for the job.', max_length=200)),
                ('experience', models.CharField(help_text='The experience required for the job.', max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True, help_text='The date and time when the job was posted.')),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('FR', 'Freelance'), ('TP', 'Temporary'), ('IN', 'Internship')], default='FT', help_text='The type of the job.', max_length=2)),
                ('category1', models.ForeignKey(blank=True, help_text='The category of the job.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.catagory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.company')),
            ],
        ),
    ]
