# Generated by Django 4.2.3 on 2023-07-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='catagory',
        ),
    ]
