# Generated by Django 4.2.3 on 2023-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/cvs/'),
        ),
    ]
